name: Release
run-name: ${{ github.event_name == 'pull_request' && 'Test' || github.event_name == 'release' && 'Release' || 'Prepare Release' }}

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '!**'
      - '.github/release-please-config.json'
      - '.github/release-please-manifest.json'
      - 'hooks/**'
  pull_request:
    branches: [main]
    paths:
      - '!**'
      - '.github/release-please-config.json'
      - '.github/release-please-manifest.json'
      - 'hooks/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release-please'))
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: block
          allowed-endpoints: ${{ vars.ALLOWED_ENDPOINTS }}
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # ratchet:dorny/paths-filter@v3.0.2
        id: filter
        with:
          list-files: json
          filters: |
            has_shell_changes:
              - 'hooks/shell/**'
      - name: Run ShellCheck
        if: steps.filter.outputs.has_shell_changes == 'true'
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # ratchet:ludeeus/action-shellcheck@2.0.0
        with:
          scandir: hooks/shell
          severity: error
          #env:
          #  SHELLCHECK_OPTS: -e SC2059 -e SC2034 -e SC1090
      # https://github.com/googleapis/release-please-action?tab=readme-ov-file#action-inputs
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # ratchet:googleapis/release-please-action@v4
        if: github.actor != 'dependabot[bot]' && github.event_name == 'push'
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          token: ${{ secrets.BOT_TOKEN }}
